"""Organizaciones, Users e Inversionistas

Revision ID: 07213a22abe3
Revises: 
Create Date: 2021-09-11 22:26:19.077930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07213a22abe3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inversionistas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inversionista_nombre', sa.String(length=20), nullable=True),
    sa.Column('inversionista_image', sa.String(length=120), nullable=True),
    sa.Column('inversionista_desc', sa.String(length=120), nullable=True),
    sa.Column('inversionista_email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inversionistas_inversionista_nombre'), 'inversionistas', ['inversionista_nombre'], unique=False)
    op.create_table('organizaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organizacion_name', sa.String(length=20), nullable=True),
    sa.Column('organizacion_image', sa.String(length=120), nullable=True),
    sa.Column('organizacion_location', sa.String(length=120), nullable=True),
    sa.Column('organizacion_phone', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizaciones_organizacion_name'), 'organizaciones', ['organizacion_name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=24), nullable=True),
    sa.Column('lastname', sa.String(length=24), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('phonenumber', sa.String(length=18), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_firstname'), 'users', ['firstname'], unique=False)
    op.create_index(op.f('ix_users_lastname'), 'users', ['lastname'], unique=False)
    op.create_index(op.f('ix_users_phonenumber'), 'users', ['phonenumber'], unique=True)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_ref', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_order_ref'), 'orders', ['order_ref'], unique=False)
    op.create_index(op.f('ix_orders_timestamp'), 'orders', ['timestamp'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=100), nullable=True),
    sa.Column('product_price', sa.Integer(), nullable=True),
    sa.Column('product_image', sa.String(length=120), nullable=True),
    sa.Column('product_description', sa.String(length=200), nullable=True),
    sa.Column('product_stock', sa.Integer(), nullable=True),
    sa.Column('product_size', sa.String(length=5), nullable=True),
    sa.Column('promotion', sa.Boolean(), nullable=True),
    sa.Column('promotion_value', sa.Integer(), nullable=True),
    sa.Column('organizacion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_product_description'), 'products', ['product_description'], unique=False)
    op.create_index(op.f('ix_products_product_name'), 'products', ['product_name'], unique=False)
    op.create_index(op.f('ix_products_product_price'), 'products', ['product_price'], unique=False)
    op.create_index(op.f('ix_products_product_size'), 'products', ['product_size'], unique=False)
    op.create_index(op.f('ix_products_product_stock'), 'products', ['product_stock'], unique=False)
    op.create_index(op.f('ix_products_promotion'), 'products', ['promotion'], unique=False)
    op.create_index(op.f('ix_products_promotion_value'), 'products', ['promotion_value'], unique=False)
    op.create_table('shippinginfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address1', sa.String(length=200), nullable=True),
    sa.Column('address2', sa.String(length=200), nullable=True),
    sa.Column('postcode', sa.String(length=12), nullable=True),
    sa.Column('city', sa.String(length=24), nullable=True),
    sa.Column('state', sa.String(length=24), nullable=True),
    sa.Column('country', sa.String(length=24), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shippinginfo_address1'), 'shippinginfo', ['address1'], unique=False)
    op.create_index(op.f('ix_shippinginfo_address2'), 'shippinginfo', ['address2'], unique=False)
    op.create_index(op.f('ix_shippinginfo_city'), 'shippinginfo', ['city'], unique=False)
    op.create_index(op.f('ix_shippinginfo_country'), 'shippinginfo', ['country'], unique=False)
    op.create_index(op.f('ix_shippinginfo_postcode'), 'shippinginfo', ['postcode'], unique=False)
    op.create_index(op.f('ix_shippinginfo_state'), 'shippinginfo', ['state'], unique=False)
    op.create_table('association',
    sa.Column('products', sa.Integer(), nullable=True),
    sa.Column('orders', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['orders'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['products'], ['products.id'], )
    )
    op.create_table('kart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('subtotal', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kart')
    op.drop_table('association')
    op.drop_index(op.f('ix_shippinginfo_state'), table_name='shippinginfo')
    op.drop_index(op.f('ix_shippinginfo_postcode'), table_name='shippinginfo')
    op.drop_index(op.f('ix_shippinginfo_country'), table_name='shippinginfo')
    op.drop_index(op.f('ix_shippinginfo_city'), table_name='shippinginfo')
    op.drop_index(op.f('ix_shippinginfo_address2'), table_name='shippinginfo')
    op.drop_index(op.f('ix_shippinginfo_address1'), table_name='shippinginfo')
    op.drop_table('shippinginfo')
    op.drop_index(op.f('ix_products_promotion_value'), table_name='products')
    op.drop_index(op.f('ix_products_promotion'), table_name='products')
    op.drop_index(op.f('ix_products_product_stock'), table_name='products')
    op.drop_index(op.f('ix_products_product_size'), table_name='products')
    op.drop_index(op.f('ix_products_product_price'), table_name='products')
    op.drop_index(op.f('ix_products_product_name'), table_name='products')
    op.drop_index(op.f('ix_products_product_description'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_orders_timestamp'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_ref'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_users_phonenumber'), table_name='users')
    op.drop_index(op.f('ix_users_lastname'), table_name='users')
    op.drop_index(op.f('ix_users_firstname'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_organizaciones_organizacion_name'), table_name='organizaciones')
    op.drop_table('organizaciones')
    op.drop_index(op.f('ix_inversionistas_inversionista_nombre'), table_name='inversionistas')
    op.drop_table('inversionistas')
    # ### end Alembic commands ###
