"""Tabla eventos

Revision ID: 5d6fe1fe286d
Revises: 07213a22abe3
Create Date: 2021-09-17 18:03:43.110217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d6fe1fe286d'
down_revision = '07213a22abe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evento_name', sa.String(length=20), nullable=True),
    sa.Column('evento_lat', sa.Float(), nullable=True),
    sa.Column('evento_long', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventos_evento_name'), 'eventos', ['evento_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eventos_evento_name'), table_name='eventos')
    op.drop_table('eventos')
    # ### end Alembic commands ###
