"""Initial migration

Revision ID: 6255ca35fa72
Revises: 
Create Date: 2021-09-10 16:41:53.053280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6255ca35fa72'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=20), nullable=True),
    sa.Column('category_image', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_category_image'), 'categories', ['category_image'], unique=False)
    op.create_index(op.f('ix_categories_category_name'), 'categories', ['category_name'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=24), nullable=True),
    sa.Column('lastname', sa.String(length=24), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('phonenumber', sa.String(length=18), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_firstname'), 'user', ['firstname'], unique=False)
    op.create_index(op.f('ix_user_lastname'), 'user', ['lastname'], unique=False)
    op.create_index(op.f('ix_user_phonenumber'), 'user', ['phonenumber'], unique=True)
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_ref', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_order_ref'), 'order', ['order_ref'], unique=False)
    op.create_index(op.f('ix_order_timestamp'), 'order', ['timestamp'], unique=False)
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=100), nullable=True),
    sa.Column('product_price', sa.Integer(), nullable=True),
    sa.Column('product_image', sa.String(length=120), nullable=True),
    sa.Column('product_description', sa.String(length=200), nullable=True),
    sa.Column('product_stock', sa.Integer(), nullable=True),
    sa.Column('product_size', sa.String(length=5), nullable=True),
    sa.Column('promotion', sa.Boolean(), nullable=False),
    sa.Column('promotion_value', sa.Integer(), nullable=False),
    sa.Column('categories_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categories_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_product_description'), 'product', ['product_description'], unique=False)
    op.create_index(op.f('ix_product_product_image'), 'product', ['product_image'], unique=False)
    op.create_index(op.f('ix_product_product_name'), 'product', ['product_name'], unique=False)
    op.create_index(op.f('ix_product_product_price'), 'product', ['product_price'], unique=False)
    op.create_index(op.f('ix_product_product_size'), 'product', ['product_size'], unique=False)
    op.create_index(op.f('ix_product_product_stock'), 'product', ['product_stock'], unique=False)
    op.create_index(op.f('ix_product_promotion'), 'product', ['promotion'], unique=False)
    op.create_index(op.f('ix_product_promotion_value'), 'product', ['promotion_value'], unique=False)
    op.create_table('shipping info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address1', sa.String(length=200), nullable=True),
    sa.Column('address2', sa.String(length=200), nullable=True),
    sa.Column('postcode', sa.String(length=12), nullable=True),
    sa.Column('city', sa.String(length=24), nullable=True),
    sa.Column('state', sa.String(length=24), nullable=True),
    sa.Column('country', sa.String(length=24), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipping info_address1'), 'shipping info', ['address1'], unique=False)
    op.create_index(op.f('ix_shipping info_address2'), 'shipping info', ['address2'], unique=False)
    op.create_index(op.f('ix_shipping info_city'), 'shipping info', ['city'], unique=False)
    op.create_index(op.f('ix_shipping info_country'), 'shipping info', ['country'], unique=False)
    op.create_index(op.f('ix_shipping info_postcode'), 'shipping info', ['postcode'], unique=False)
    op.create_index(op.f('ix_shipping info_state'), 'shipping info', ['state'], unique=False)
    op.create_table('association',
    sa.Column('product', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order'], ['order.id'], ),
    sa.ForeignKeyConstraint(['product'], ['product.id'], )
    )
    op.create_table('kart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('subtotal', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kart')
    op.drop_table('association')
    op.drop_index(op.f('ix_shipping info_state'), table_name='shipping info')
    op.drop_index(op.f('ix_shipping info_postcode'), table_name='shipping info')
    op.drop_index(op.f('ix_shipping info_country'), table_name='shipping info')
    op.drop_index(op.f('ix_shipping info_city'), table_name='shipping info')
    op.drop_index(op.f('ix_shipping info_address2'), table_name='shipping info')
    op.drop_index(op.f('ix_shipping info_address1'), table_name='shipping info')
    op.drop_table('shipping info')
    op.drop_index(op.f('ix_product_promotion_value'), table_name='product')
    op.drop_index(op.f('ix_product_promotion'), table_name='product')
    op.drop_index(op.f('ix_product_product_stock'), table_name='product')
    op.drop_index(op.f('ix_product_product_size'), table_name='product')
    op.drop_index(op.f('ix_product_product_price'), table_name='product')
    op.drop_index(op.f('ix_product_product_name'), table_name='product')
    op.drop_index(op.f('ix_product_product_image'), table_name='product')
    op.drop_index(op.f('ix_product_product_description'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_order_timestamp'), table_name='order')
    op.drop_index(op.f('ix_order_order_ref'), table_name='order')
    op.drop_table('order')
    op.drop_index(op.f('ix_user_phonenumber'), table_name='user')
    op.drop_index(op.f('ix_user_lastname'), table_name='user')
    op.drop_index(op.f('ix_user_firstname'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_categories_category_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_category_image'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
