"""Quite el promocion:booleano y agregue validador de positivos

Revision ID: 966b67bffab7
Revises: 5d6fe1fe286d
Create Date: 2021-09-20 22:19:30.848143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '966b67bffab7'
down_revision = '5d6fe1fe286d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_cant', sa.String(length=5), nullable=True))
    op.drop_index('ix_products_product_size', table_name='products')
    op.drop_index('ix_products_promotion', table_name='products')
    op.create_index(op.f('ix_products_product_cant'), 'products', ['product_cant'], unique=False)
    op.drop_column('products', 'product_size')
    op.drop_column('products', 'promotion')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('promotion', sa.BOOLEAN(), nullable=True))
    op.add_column('products', sa.Column('product_size', sa.VARCHAR(length=5), nullable=True))
    op.drop_index(op.f('ix_products_product_cant'), table_name='products')
    op.create_index('ix_products_promotion', 'products', ['promotion'], unique=False)
    op.create_index('ix_products_product_size', 'products', ['product_size'], unique=False)
    op.drop_column('products', 'product_cant')
    # ### end Alembic commands ###
