"""Initial migration

Revision ID: dd9537533cdf
Revises: 
Create Date: 2021-09-25 21:54:26.553945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd9537533cdf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evento_name', sa.String(length=20), nullable=True),
    sa.Column('evento_lat', sa.Float(), nullable=True),
    sa.Column('evento_long', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventos_evento_name'), 'eventos', ['evento_name'], unique=False)
    op.create_table('inversionistas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inversionista_name', sa.String(length=20), nullable=True),
    sa.Column('inversionista_image', sa.String(length=120), nullable=True),
    sa.Column('inversionista_desc', sa.String(length=120), nullable=True),
    sa.Column('inversionista_email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inversionistas_inversionista_name'), 'inversionistas', ['inversionista_name'], unique=False)
    op.create_table('organizaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organizacion_name', sa.String(length=20), nullable=True),
    sa.Column('organizacion_image', sa.String(length=120), nullable=True),
    sa.Column('organizacion_location', sa.String(length=120), nullable=True),
    sa.Column('organizacion_phone', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizaciones_organizacion_name'), 'organizaciones', ['organizacion_name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=24), nullable=True),
    sa.Column('lastname', sa.String(length=24), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('phonenumber', sa.String(length=18), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_firstname'), 'users', ['firstname'], unique=False)
    op.create_index(op.f('ix_users_lastname'), 'users', ['lastname'], unique=False)
    op.create_index(op.f('ix_users_phonenumber'), 'users', ['phonenumber'], unique=True)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=100), nullable=True),
    sa.Column('product_price', sa.Integer(), nullable=True),
    sa.Column('product_image', sa.String(length=120), nullable=True),
    sa.Column('product_description', sa.String(length=200), nullable=True),
    sa.Column('product_stock', sa.Integer(), nullable=True),
    sa.Column('promotion_value', sa.Integer(), nullable=True),
    sa.Column('organizacion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_product_name'), 'products', ['product_name'], unique=False)
    op.create_index(op.f('ix_products_product_price'), 'products', ['product_price'], unique=False)
    op.create_index(op.f('ix_products_promotion_value'), 'products', ['promotion_value'], unique=False)
    op.create_table('shipping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('aditional_indications', sa.String(length=200), nullable=True),
    sa.Column('postcode', sa.String(length=12), nullable=True),
    sa.Column('city', sa.String(length=24), nullable=True),
    sa.Column('state', sa.String(length=24), nullable=True),
    sa.Column('country', sa.String(length=24), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipping_address'), 'shipping', ['address'], unique=False)
    op.create_index(op.f('ix_shipping_aditional_indications'), 'shipping', ['aditional_indications'], unique=False)
    op.create_index(op.f('ix_shipping_city'), 'shipping', ['city'], unique=False)
    op.create_index(op.f('ix_shipping_country'), 'shipping', ['country'], unique=False)
    op.create_index(op.f('ix_shipping_postcode'), 'shipping', ['postcode'], unique=False)
    op.create_index(op.f('ix_shipping_state'), 'shipping', ['state'], unique=False)
    op.create_table('kart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('subtotal', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('shipping_id', sa.Integer(), nullable=True),
    sa.Column('kart_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kart_id'], ['kart.id'], ),
    sa.ForeignKeyConstraint(['shipping_id'], ['shipping.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_timestamp'), 'orders', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_timestamp'), table_name='orders')
    op.drop_table('orders')
    op.drop_table('kart')
    op.drop_index(op.f('ix_shipping_state'), table_name='shipping')
    op.drop_index(op.f('ix_shipping_postcode'), table_name='shipping')
    op.drop_index(op.f('ix_shipping_country'), table_name='shipping')
    op.drop_index(op.f('ix_shipping_city'), table_name='shipping')
    op.drop_index(op.f('ix_shipping_aditional_indications'), table_name='shipping')
    op.drop_index(op.f('ix_shipping_address'), table_name='shipping')
    op.drop_table('shipping')
    op.drop_index(op.f('ix_products_promotion_value'), table_name='products')
    op.drop_index(op.f('ix_products_product_price'), table_name='products')
    op.drop_index(op.f('ix_products_product_name'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_users_phonenumber'), table_name='users')
    op.drop_index(op.f('ix_users_lastname'), table_name='users')
    op.drop_index(op.f('ix_users_firstname'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_organizaciones_organizacion_name'), table_name='organizaciones')
    op.drop_table('organizaciones')
    op.drop_index(op.f('ix_inversionistas_inversionista_name'), table_name='inversionistas')
    op.drop_table('inversionistas')
    op.drop_index(op.f('ix_eventos_evento_name'), table_name='eventos')
    op.drop_table('eventos')
    # ### end Alembic commands ###
